/**
 * @type {import('@remix-run/dev').AppConfig}
 */
module.exports = {
    future: {
        unstable_postcss: true,
        unstable_tailwind: true,
        v2_routeConvention: true,
    },
    // When running locally in development mode, we use the built in remix
    // server. This does not understand the vercel lambda module format,
    // so we default back to the standard build output.
    ignoredRouteFiles: ['**/.*'],
    // appDirectory: "app",
    // assetsBuildDirectory: "public/build",
    // serverBuildPath: "api/index.js",
    // publicPath: "/build/",
    serverDependenciesToBundle: [
        '@aurelius/writer',
        /^@mdx-js*/,
        'bail',
        'ccount',
        /^character-*/,
        'comma-separated-tokens',
        'decode-named-character-reference',
        /^estree-util-*/,
        'estree-walker',
        'fault',
        'gray-matter',
        /^hast-util-*/,
        /^is-*/,
        'lowlight',
        /^mdast-util-*/,
        /^micromark*/,
        /^nanoid*/,
        'parse-entities',
        'periscopic',
        'property-information',
        /^remark-*/,
        'space-separated-tokens',
        'stringify-entities',
        'trim-lines',
        'trough',
        'unified',
        /^unist-util-*/,
        /^vfile*/,
        'zwitch',
    ],
    watchPaths: ['../../packages/aurelius'],
}
